runners:
  -
    tag: "Unconditional Cooperator vs Random"
    iterations: 50
    solver: smp
    strategies:
      - cu
      - rand
  -
    tag: "Random vs Tip fot Tip"
    iterations: 50
    solver: smp
    strategies:
      - rand
      - tft
  -
    tag: "Unconditional Defector vs Tip fot Tip"
    iterations: 50
    solver: smp
    strategies:
      - du
      - tft
  -
    tag: "Tit for Two Tats vs Tip fot Tip"
    iterations: 50
    solver: smp
    strategies:
      - tftt
      - tft

viewers:
  -
    type: html
    out: ./results/result.html
  -
    type: text
    out: ./results/result.text
  -
    type: json
    out: ./results/result.json
